---
- name: Get packages needed for the install process
  apt:
    name:
      - curl 
      - apt-transport-https
      - lsb-release
      - gnupg
    update_cache: yes 
    cache_valid_time: 3600
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Download and install the Microsoft signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present

- name: Add the Microsoft Azure CLI software repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ stretch main
    state: present
    filename: azure-cli

- name: Update repository information and install the azure-cli package
  apt:
    name:
      - azure-cli
    update_cache: yes 
    cache_valid_time: 3600
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
